!!python/object:nvf.nerfstudio_interface.nbv_trainer.NBVTrainerConfig
_target: !!python/name:nvf.nerfstudio_interface.nbv_trainer.NBVTrainer ''
data: !!python/object/apply:pathlib.PosixPath
- /
- attached
- remote-home2
- zzq
- 05-offline-NeRF-based-NBV
- outputs
- pipeline
- dataset
draw_training_images: false
experiment_name: dataset
gradient_accumulation_steps: 1
load_checkpoint: null
load_config: null
load_dir: null
load_file: null
load_step: null
log_gradients: false
logging: !!python/object:nerfstudio.configs.base_config.LoggingConfig
  local_writer: !!python/object:nerfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:nerfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 1
    stats_to_track: !!python/tuple
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - ETA (time)
  max_buffer_size: 20
  profiler: basic
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:nerfstudio.configs.base_config.MachineConfig
  device_type: cuda
  dist_url: auto
  machine_rank: 0
  num_devices: 1
  num_machines: 1
  seed: 42
max_num_iterations: 10000
method_name: instant-ngp
mixed_precision: true
num_imgs_to_start: 1
optimizers:
  fields:
    optimizer: !!python/object:nerfstudio.engine.optimizers.OptimizerConfig
      _target: &id001 !!python/name:torch.optim.adam.Adam ''
      eps: 1.0e-15
      lr: 0.01
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: &id002 !!python/name:nerfstudio.engine.schedulers.ExponentialDecayScheduler ''
      lr_final: 0.0001
      lr_pre_warmup: 1.0e-08
      max_steps: 10000
      ramp: cosine
      warmup_steps: 0
output_dir: !!python/object/apply:pathlib.PosixPath
- cfg
- config
pipeline: !!python/object:nerfstudio.pipelines.dynamic_batch.DynamicBatchPipelineConfig
  _target: !!python/name:nerfstudio.pipelines.dynamic_batch.DynamicBatchPipeline ''
  datamanager: !!python/object:nvf.nerfstudio_interface.nbv_datamanager.NBVDataManagerConfig
    _target: !!python/name:nvf.nerfstudio_interface.nbv_datamanager.NBVDataManager ''
    camera_optimizer: !!python/object:nerfstudio.cameras.camera_optimizers.CameraOptimizerConfig
      _target: !!python/name:nerfstudio.cameras.camera_optimizers.CameraOptimizer ''
      mode: 'off'
      optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
        _target: *id001
        eps: 1.0e-15
        lr: 0.0006
        max_norm: null
        weight_decay: 0
      orientation_noise_std: 0.0
      param_group: camera_opt
      position_noise_std: 0.0
      scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
        _target: *id002
        lr_final: null
        lr_pre_warmup: 1.0e-08
        max_steps: 10000
        ramp: cosine
        warmup_steps: 0
    camera_res_scale_factor: 1.0
    collate_fn: !!python/name:nerfstudio.data.utils.nerfstudio_collate.nerfstudio_collate ''
    data: !!python/object/apply:pathlib.PosixPath
    - /
    - attached
    - remote-home2
    - zzq
    - 05-offline-NeRF-based-NBV
    - outputs
    - pipeline
    - dataset
    dataparser: !!python/object:nvf.nerfstudio_interface.nbv_dataparser.NBVDataParserConfig
      _target: !!python/name:nvf.nerfstudio_interface.nbv_dataparser.NBVDataParser ''
      data: !!python/object/apply:pathlib.PosixPath
      - /
      - attached
      - remote-home2
      - zzq
      - 05-offline-NeRF-based-NBV
      - outputs
      - pipeline
      - dataset
      fov: 90
      height: 512
      scene_scale: 1
      width: 512
    eval_image_indices: !!python/tuple
    - 0
    eval_num_images_to_sample_from: -1
    eval_num_rays_per_batch: 4096
    eval_num_times_to_repeat_images: -1
    masks_on_gpu: null
    num_training_images: 401
    patch_size: 1
    train_num_images_to_sample_from: -1
    train_num_rays_per_batch: 4096
    train_num_times_to_repeat_images: -1
  max_dynamic_num_rays_per_batch: 87381
  max_num_samples_per_ray: 1024
  model: !!python/object:nerfstudio.models.instant_ngp.InstantNGPModelConfig
    _target: !!python/name:nerfstudio.models.instant_ngp.NGPModel ''
    alpha_thre: 0.01
    background_color: random
    collider_params: null
    cone_angle: 0.004
    disable_scene_contraction: true
    enable_collider: false
    eval_num_rays_per_batch: 8192
    eval_num_rays_per_chunk: 4096
    far_plane: 1000.0
    grid_levels: 4
    grid_resolution: 128
    log2_hashmap_size: 19
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    max_res: 512
    near_plane: 0.05
    prompt: null
    render_step_size: null
    use_active_nerf: false
    use_appearance_embedding: false
    use_neur_ar: false
    use_opacity_renderer: false
  target_num_samples: 262144
project_name: nerfstudio-project
prompt: null
relative_model_dir: !!python/object/apply:pathlib.PosixPath
- nerfstudio_models
save_only_latest_checkpoint: true
steps_per_eval_all_images: 25000
steps_per_eval_batch: 500
steps_per_eval_image: 500
steps_per_save: 200
timestamp: latest_checkpoint
use_grad_scaler: false
viewer: !!python/object:nerfstudio.configs.base_config.ViewerConfig
  image_format: jpeg
  jpeg_quality: 90
  max_num_display_images: 512
  num_rays_per_chunk: 4096
  quit_on_train_completion: true
  relative_log_filename: viewer_log_filename.txt
  websocket_host: 0.0.0.0
  websocket_port: 7007
  websocket_port_default: 7007
vis: viewer
